worker_processes auto;

events {
    worker_connections 1024;
}

http {

    # upstream prod {
    #     server production:3000;
    # }

    upstream dev {
        server development:3001;
    }

    # upstream test {
    #     server testing:3002;
    # }

    # upstream preprod {
    #     server preproduction:3003;
    # }

    server {
        listen 80;

        # location / {
        #     proxy_pass http://prod;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }

        location /dev {
            proxy_pass http://dev;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # location /qa {
        #     proxy_pass http://test;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }

        # location /alfa {
        #     proxy_pass http://preprod;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}